/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedInboxRouteRouteImport } from './routes/_authenticated/inbox/route'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated/inbox/index'
import { Route as AuthenticatedInboxConversationIdRouteImport } from './routes/_authenticated/inbox/$conversationId'
import { Route as ApiPublicMspWebhookRouteImport } from './routes/api/public/msp-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInboxRouteRoute = AuthenticatedInboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedInboxRouteRoute,
} as any)
const AuthenticatedInboxConversationIdRoute =
  AuthenticatedInboxConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedInboxRouteRoute,
  } as any)
const ApiPublicMspWebhookRoute = ApiPublicMspWebhookRouteImport.update({
  id: '/api/public/msp-webhook',
  path: '/api/public/msp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/inbox': typeof AuthenticatedInboxRouteRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRoute
  '/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/api/public/msp-webhook': typeof ApiPublicMspWebhookRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/api/public/msp-webhook': typeof ApiPublicMspWebhookRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteRouteWithChildren
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/api/public/msp-webhook': typeof ApiPublicMspWebhookRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/inbox'
    | '/templates'
    | '/inbox/$conversationId'
    | '/api/public/msp-webhook'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/templates'
    | '/inbox/$conversationId'
    | '/api/public/msp-webhook'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/inbox'
    | '/_authenticated/templates'
    | '/_authenticated/inbox/$conversationId'
    | '/api/public/msp-webhook'
    | '/_authenticated/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMspWebhookRoute: typeof ApiPublicMspWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedInboxRouteRoute
    }
    '/_authenticated/inbox/$conversationId': {
      id: '/_authenticated/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof AuthenticatedInboxConversationIdRouteImport
      parentRoute: typeof AuthenticatedInboxRouteRoute
    }
    '/api/public/msp-webhook': {
      id: '/api/public/msp-webhook'
      path: '/api/public/msp-webhook'
      fullPath: '/api/public/msp-webhook'
      preLoaderRoute: typeof ApiPublicMspWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedInboxRouteRouteChildren {
  AuthenticatedInboxConversationIdRoute: typeof AuthenticatedInboxConversationIdRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
}

const AuthenticatedInboxRouteRouteChildren: AuthenticatedInboxRouteRouteChildren =
  {
    AuthenticatedInboxConversationIdRoute:
      AuthenticatedInboxConversationIdRoute,
    AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
  }

const AuthenticatedInboxRouteRouteWithChildren =
  AuthenticatedInboxRouteRoute._addFileChildren(
    AuthenticatedInboxRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInboxRouteRoute: typeof AuthenticatedInboxRouteRouteWithChildren
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInboxRouteRoute: AuthenticatedInboxRouteRouteWithChildren,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMspWebhookRoute: ApiPublicMspWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
